# Generated by Django 6.0.1 on 2026-02-14 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_code_alter_category_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
