# Generated by Django 6.0.1 on 2026-03-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_onboarding_fields'),
        ('profiles', '0003_profile_created_at_settings_updated_at'),
    ]

    operations = [
    ]
