# Generated by Django 6.0.1 on 2026-03-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_merge_20260311_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Nigeria', 'Nigeria'), ('South Africa', 'South Africa'), ('United States', 'United States'), ('Mexico', 'Mexico'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('India', 'India'), ('Italy', 'Italy'), ('China', 'China'), ('Germany', 'Germany'), ('France', 'France'), ('Japan', 'Japan'), ('Ghana', 'Ghana'), ('Egypt', 'Egypt'), ('Brazil', 'Brazil'), ('Australia', 'Australia'), ('Argentina', 'Argentina'), ('Peru', 'Peru'), ('New Zealand', 'New Zealand'), ('Nepal', 'Nepal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
