# Generated by Django 6.0.1 on 2026-02-02 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORTATION', 'Transportation'), ('ACADEMIC', 'Academic'), ('BILLS AND UTILITIES', 'Bills andUtilities'), ('SUBSCRIPTIONS', 'Subscriptions'), ('HEALTH AND FITNESS', 'Health and Fitness'), ('MISCELLANEOUS', 'Miscellaneous')], default='MISCELLANEOUS', max_length=40),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORTATION', 'Transportation'), ('ACADEMIC', 'Academic'), ('BILLS AND UTILITIES', 'Bills andUtilities'), ('SUBSCRIPTIONS', 'Subscriptions'), ('HEALTH AND FITNESS', 'Health and Fitness'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=40)),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
