# Generated by Django 6.0.1 on 2026-02-13 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('transactions', '0002_transaction_category_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='category.category'),
        ),
    ]
