# Generated by Django 6.0.1 on 2026-02-14 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
