# Generated by Django 6.0.1 on 2026-02-15 10:28

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def delete_duplicate_transactions(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    dupes = (
        Transaction.objects
        .values('workspace_id', 'client_id')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    for d in dupes:
        qs = (
            Transaction.objects
            .filter(workspace_id=d['workspace_id'], client_id=d['client_id'])
            .order_by('-updated_at', '-id')
        )
        ids_to_delete = list(qs.values_list('id', flat=True)[1:])
        if ids_to_delete:
            Transaction.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_code'),
        ('transactions', '0005_transaction_client_id_transaction_deleted_at_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_transactions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('workspace', 'client_id'), name='uniq_txn_per_workspace_client'),
        ),
    ]
