# Generated by Django 6.0.1 on 2026-02-16 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_code'),
        ('transactions', '0006_transaction_uniq_txn_per_workspace_client'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['workspace', 'updated_at', 'id'], name='transaction_workspa_733153_idx'),
        ),
    ]
