# Generated by Django 6.0.1 on 2026-02-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_transaction_workspa_733153_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
    ]
