# Generated by Django 6.0.1 on 2026-03-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_normalize_transaction_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category_obj',
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORTATION', 'Transportation'), ('ACADEMICS', 'Academics'), ('BILLS AND UTILITIES', 'Bills andUtilities'), ('SUBSCRIPTIONS', 'Subscriptions'), ('HEALTH AND FITNESS', 'Health and Fitness'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORTATION', 'Transportation'), ('ACADEMICS', 'Academics'), ('BILLS AND UTILITIES', 'Bills andUtilities'), ('SUBSCRIPTIONS', 'Subscriptions'), ('HEALTH AND FITNESS', 'Health and Fitness'), ('MISCELLANEOUS', 'Miscellaneous')], default='MISCELLANEOUS', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10),
        ),
    ]
