# Generated by Django 6.0.1 on 2026-04-01 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_kind'),
        ('transactions', '0011_remove_budget_category_remove_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='category.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='category.category'),
        ),
    ]
