# Generated by Django 6.0.1 on 2026-02-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_rename_statements_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='statement',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
