# Generated by Django 6.0.1 on 2026-02-11 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_statement_bank_name_statement_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='statement',
            new_name='BankStatement',
        ),
    ]
