# Generated by Django 6.0.1 on 2026-02-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_name", models.CharField(max_length=120)),
                ("account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=120)),
                ("account_type", models.CharField(choices=[("INDIVIDUAL", "Individual"), ("FAMILY", "Family"), ("BUSINESS", "Business")], default="INDIVIDUAL", max_length=20)),
                ("amount_ngn", models.PositiveIntegerField()),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="billing_accounts", to="users.user")),
            ],
        ),
    ]
