# Generated by Django 6.0.1 on 2026-03-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_email_verified'),
        ('users', '0004_billing_account'),
    ]

    operations = [
    ]
