"""
Django settings for wolex_backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django import http
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!

from decouple import config

from decouple import config

SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = ['*']  # lock down in production

# CORS configuration – frontends should specify origins via environment.  when hard‑
# coded they must be a list/tuple of strings.
# settings.py

# Keep your existing CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5500",
    "http://localhost:5500",
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    "https://wolex-frontend.vercel.app",
]

# ADD THIS: CSRF needs its own list of trusted origins
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5500",
    "http://localhost:5500",
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    "https://wolex-frontend.vercel.app",

]
CORS_ALLOW_CREDENTIALS = True
# external services / env keys
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')
FRONTEND_URL = config(
    'FRONTEND_URL',
    default='https://wolex-frontend.vercel.app'
)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@wolex.com')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'apps.users',
    'apps.transactions',
    'apps.alerts',
    'apps.profiles',
    'apps.core',
    'apps.statements',
    'apps.chatbot',
    'apps.activity',
    'apps.category',
    'apps.workspaces',
    'apps.sync'

]

# Include django_q only if compatible (some django-q versions require older Django utilities)
try:
    # ensure django.utils.baseconv exists (django-q expects it on import)
    from django.utils import baseconv  # type: ignore
except Exception:
    # incompatible Django or django-q dependency missing; do not enable django_q
    pass
else:
    try:
        import django_q  # type: ignore
    except Exception:
        # django_q import failed; skip enabling the app
        pass
    else:
        INSTALLED_APPS.append('django_q')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wolex_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wolex_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url
from decouple import config

DATABASES = {
    "default": dj_database_url.config(
        default=config(
            "DATABASE_URL",
            # '#' must be percent-encoded in URLs
            default="postgres://postgres:Wondermentdb%232009@127.0.0.1:5432/wolex_db"
        ),
        conn_max_age=600,
    )
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },    {
        'NAME': 'apps.users.validators.SymbolNumberPasswordValidator',
    },]

AUTH_USER_MODEL = 'users.User'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "1000/day",
        "anon": "100/day",
        "chatbot": "30/min",
        "auth": "20/hour",
        "password_reset": "10/hour",
        "email_verification": "10/hour",
        "google_auth": "20/hour",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",

}

from datetime import timedelta

SIMPLE_JWT = {
    # Set the Access Token to last 24 hours
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    # Set the Refresh Token to last 7 days
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}



SPECTACULAR_SETTINGS = {
    'TITLE': 'Wolex API',
    'DESCRIPTION': 'Backend API for Wolex - users, transactions, statements, and context services.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# Django Q settings (only if django_q is installed and compatible)

Q_CLUSTER = {
    "name": "Wolex",
    "workers": 4,
    "recycle": 500,
    "timeout": 60,
    "retry": 120,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers" : ["console"],
        "level" : "INFO"
    },
}




# This redirects all emails to your terminal instead of a real server
LOGIN_REDIRECT_URL = '/pages/dashboard.html'
